<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>

    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>

    <LangVersion>latest</LangVersion>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.10.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.10.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
	<PackageReference Include="MSTest.TestFramework" Version="3.2.2" />
	<PackageReference Include="MSTest.TestAdapter" Version="3.2.2" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\Webpay.Integration.CSharp\Webpay.Integration.CSharp.csproj" />
  </ItemGroup>

</Project>