<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>

    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
	 <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>

    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
	<PackageReference Include="MSTest.TestFramework" Version="3.2.2" />
	<PackageReference Include="MSTest.TestAdapter" Version="3.2.2" />
	<Reference Include="System.Web" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Webpay.Integration.CSharp\Webpay.Integration.CSharp.csproj" />
  </ItemGroup>

</Project>